apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arohan-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: arohan.health
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: arohan-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: arohan-frontend
            port:
              number: 80
