apiVersion: v1
kind: Service
metadata:
  name: arohan-backend
spec:
  selector:
    app: arohan-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: arohan-frontend
spec:
  selector:
    app: arohan-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
